//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocabulary.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vocabulary.Web.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add all To Vocabulary.
        /// </summary>
        public static string AddAllToVocabulary {
            get {
                return ResourceManager.GetString("AddAllToVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add as learned.
        /// </summary>
        public static string AddPhraseAsLearned {
            get {
                return ResourceManager.GetString("AddPhraseAsLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add phrase to vocabulary as learned.
        /// </summary>
        public static string AddPhraseAsLearnedTitle {
            get {
                return ResourceManager.GetString("AddPhraseAsLearnedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add as unknown.
        /// </summary>
        public static string AddPhraseAsUnknown {
            get {
                return ResourceManager.GetString("AddPhraseAsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add phrase to vocabulary as unknown.
        /// </summary>
        public static string AddPhraseAsUnknownTitle {
            get {
                return ResourceManager.GetString("AddPhraseAsUnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add phrase to vocabulary.
        /// </summary>
        public static string AddPhraseToVocabulary {
            get {
                return ResourceManager.GetString("AddPhraseToVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glossaries main page.
        /// </summary>
        public static string AdminGlossariesTitle {
            get {
                return ResourceManager.GetString("AdminGlossariesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already added to vocabulary.
        /// </summary>
        public static string AlreadyAddedToVocabulary {
            get {
                return ResourceManager.GetString("AlreadyAddedToVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enable/disable autoplay.
        /// </summary>
        public static string AutoplayTitle {
            get {
                return ResourceManager.GetString("AutoplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Begin.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change size of widget(with or without examples).
        /// </summary>
        public static string ChangeVidgetSize {
            get {
                return ResourceManager.GetString("ChangeVidgetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose translation language:.
        /// </summary>
        public static string ChooseTranslationLanguage {
            get {
                return ResourceManager.GetString("ChooseTranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email is already exist.
        /// </summary>
        public static string EmailAlreadyExist {
            get {
                return ResourceManager.GetString("EmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email should contain only latin letters and numbers..
        /// </summary>
        public static string EmailParameterError {
            get {
                return ResourceManager.GetString("EmailParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Examples.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User with such username isn&apos;t exist.
        /// </summary>
        public static string ExistUsernameError {
            get {
                return ResourceManager.GetString("ExistUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glossaries.
        /// </summary>
        public static string Glossaries {
            get {
                return ResourceManager.GetString("Glossaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Glossary - .
        /// </summary>
        public static string Glossary {
            get {
                return ResourceManager.GetString("Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Learning state.
        /// </summary>
        public static string LearningState {
            get {
                return ResourceManager.GetString("LearningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open glossary.
        /// </summary>
        public static string OpenGlossary {
            get {
                return ResourceManager.GetString("OpenGlossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на out of.
        /// </summary>
        public static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pasword should contain only latin letters and numbers. Minimum 6, maximum 16 symbols..
        /// </summary>
        public static string PasswordParameterError {
            get {
                return ResourceManager.GetString("PasswordParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phrase.
        /// </summary>
        public static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phrases.
        /// </summary>
        public static string Phrases {
            get {
                return ResourceManager.GetString("Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phrases main page.
        /// </summary>
        public static string PhrasesTitle {
            get {
                return ResourceManager.GetString("PhrasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play audio.
        /// </summary>
        public static string PlayAudio {
            get {
                return ResourceManager.GetString("PlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous page.
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove phrase from vocabulary.
        /// </summary>
        public static string RemovePhraseFromVocabulary {
            get {
                return ResourceManager.GetString("RemovePhraseFromVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove selected phrases from vocabulary.
        /// </summary>
        public static string RemovePhrasesFromVocabulary {
            get {
                return ResourceManager.GetString("RemovePhrasesFromVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search query....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected glossaries language.
        /// </summary>
        public static string SelectedGlossaryLanguage {
            get {
                return ResourceManager.GetString("SelectedGlossaryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected phrases translations language.
        /// </summary>
        public static string SelectedTranslationLanguage {
            get {
                return ResourceManager.GetString("SelectedTranslationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select glossaries in english language.
        /// </summary>
        public static string SelectGlossaryEnLanguage {
            get {
                return ResourceManager.GetString("SelectGlossaryEnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select glossaries in russian language.
        /// </summary>
        public static string SelectGlossaryRuLanguage {
            get {
                return ResourceManager.GetString("SelectGlossaryRuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select glossaries in ukrainian language.
        /// </summary>
        public static string SelectGlossaryUkLanguage {
            get {
                return ResourceManager.GetString("SelectGlossaryUkLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select phrases translations in english language.
        /// </summary>
        public static string SelectTranslationEnLanguage {
            get {
                return ResourceManager.GetString("SelectTranslationEnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select phrases translations in russian language.
        /// </summary>
        public static string SelectTranslationRuLanguage {
            get {
                return ResourceManager.GetString("SelectTranslationRuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select phrases translations in ukrainian language.
        /// </summary>
        public static string SelectTranslationUkLanguage {
            get {
                return ResourceManager.GetString("SelectTranslationUkLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sentences.
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello,.
        /// </summary>
        public static string SignInAs {
            get {
                return ResourceManager.GetString("SignInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something is going wrong!.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phrases sets.
        /// </summary>
        public static string UserGlossariesTitle {
            get {
                return ResourceManager.GetString("UserGlossariesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username is already exist.
        /// </summary>
        public static string UsernameAlreadyExist {
            get {
                return ResourceManager.GetString("UsernameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username or password is incorrect.
        /// </summary>
        public static string UsernameOrPasswordIncorrent {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIncorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username should contain only latin letters and numbers and begin with a letter. Minimum 5, maximum 30 symbols..
        /// </summary>
        public static string UsernameParameterError {
            get {
                return ResourceManager.GetString("UsernameParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vocabulary.
        /// </summary>
        public static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Vocabulary .
        /// </summary>
        public static string VocabularyTitle {
            get {
                return ResourceManager.GetString("VocabularyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Words.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Word rank.
        /// </summary>
        public static string WordRank {
            get {
                return ResourceManager.GetString("WordRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на words.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
